../icons/granatier-16.xpm /usr/share/pixmaps
../icons/granatier.xpm /usr/share/pixmaps
usr/games/granatier
usr/share/applications/kde4/granatier.desktop
usr/share/doc/kde4/HTML/en/granatier/*
usr/share/icons/hicolor/128x128/apps/granatier.png
usr/share/icons/hicolor/16x16/apps/granatier.png
usr/share/icons/hicolor/22x22/apps/granatier.png
usr/share/icons/hicolor/32x32/apps/granatier.png
usr/share/icons/hicolor/48x48/apps/granatier.png
usr/share/icons/hicolor/64x64/apps/granatier.png
usr/share/icons/hicolor/scalable/apps/granatier.svgz
usr/share/kde4/apps/granatier/*
usr/share/kde4/config.kcfg/granatier.kcfg
