usr/games/kapman
usr/share/applications/kde4/kapman.desktop
usr/share/doc/kde4/HTML/en/kapman/
usr/share/icons/hicolor/scalable/apps/kapman.svgz
usr/share/kde4/apps/kapman/
usr/share/sounds/kapman/
usr/share/icons/hicolor/128x128/apps/kapman.png
usr/share/icons/hicolor/16x16/apps/kapman.png
usr/share/icons/hicolor/22x22/apps/kapman.png
usr/share/icons/hicolor/32x32/apps/kapman.png
usr/share/icons/hicolor/48x48/apps/kapman.png
usr/share/icons/hicolor/64x64/apps/kapman.png

