../icons/kbackgammon-16.xpm /usr/share/pixmaps
../icons/kbackgammon.xpm /usr/share/pixmaps
/usr/games/kbackgammon
/usr/share/applications/kde4/kbackgammon.desktop
/usr/share/doc/kde4/HTML/en/kbackgammon/*
/usr/share/icons/hicolor/128x128/apps/kbackgammon.png
/usr/share/icons/hicolor/16x16/apps/kbackgammon_engine.png
/usr/share/icons/hicolor/16x16/apps/kbackgammon.png
/usr/share/icons/hicolor/22x22/apps/kbackgammon.png
/usr/share/icons/hicolor/32x32/apps/kbackgammon_engine.png
/usr/share/icons/hicolor/32x32/apps/kbackgammon.png
/usr/share/icons/hicolor/48x48/apps/kbackgammon_engine.png
/usr/share/icons/hicolor/48x48/apps/kbackgammon.png
/usr/share/icons/hicolor/64x64/apps/kbackgammon_engine.png
/usr/share/icons/hicolor/64x64/apps/kbackgammon.png
/usr/share/kde4/apps/kbackgammon/*
