../icons/kbounce-16.xpm /usr/share/pixmaps
../icons/kbounce.xpm /usr/share/pixmaps
usr/games/kbounce
usr/share/applications/kde4/kbounce.desktop
usr/share/doc/kde/HTML/en/kbounce/*
usr/share/icons/hicolor/128x128/apps/kbounce.png
usr/share/icons/hicolor/16x16/apps/kbounce.png
usr/share/icons/hicolor/22x22/apps/kbounce.png
usr/share/icons/hicolor/32x32/apps/kbounce.png
usr/share/icons/hicolor/48x48/apps/kbounce.png
usr/share/icons/hicolor/64x64/apps/kbounce.png
usr/share/kde4/apps/kbounce/*
