../icons/kgoldrunner-16.xpm /usr/share/pixmaps
../icons/kgoldrunner.xpm /usr/share/pixmaps
etc/kde4/kgoldrunner.knsrc
usr/games/kgoldrunner
usr/share/applications/kde4/KGoldrunner.desktop
usr/share/doc/kde4/HTML/en/kgoldrunner/*
usr/share/icons/hicolor/128x128/apps/kgoldrunner.png
usr/share/icons/hicolor/16x16/apps/kgoldrunner.png
usr/share/icons/hicolor/22x22/apps/kgoldrunner.png
usr/share/icons/hicolor/32x32/apps/kgoldrunner.png
usr/share/icons/hicolor/48x48/apps/kgoldrunner.png
usr/share/icons/hicolor/64x64/apps/kgoldrunner.png
usr/share/kde4/apps/kgoldrunner/*
