/usr/games/kiriki
/usr/share/applications/kde4/kiriki.desktop
/usr/share/apps/kiriki
/usr/share/doc/kde/HTML/en/kiriki
/usr/share/icons/hicolor/16x16/apps/kiriki.png
/usr/share/icons/hicolor/22x22/apps/kiriki.png
/usr/share/icons/hicolor/32x32/apps/kiriki.png
/usr/share/icons/hicolor/48x48/apps/kiriki.png
/usr/share/icons/hicolor/64x64/apps/kiriki.png
/usr/share/icons/hicolor/128x128/apps/kiriki.png
../icons/kiriki.xpm /usr/share/pixmaps
../icons/kiriki-16.xpm /usr/share/pixmaps
