../icons/kjumpingcube-16.xpm /usr/share/pixmaps
../icons/kjumpingcube.xpm /usr/share/pixmaps
usr/games/kjumpingcube
usr/share/applications/kde4/kjumpingcube.desktop
usr/share/doc/kde4/HTML/en/kjumpingcube/common
usr/share/doc/kde4/HTML/en/kjumpingcube/index.cache.bz2
usr/share/doc/kde4/HTML/en/kjumpingcube/index.docbook
usr/share/icons/hicolor/128x128/apps/kjumpingcube.png
usr/share/icons/hicolor/16x16/apps/kjumpingcube.png
usr/share/icons/hicolor/22x22/apps/kjumpingcube.png
usr/share/icons/hicolor/32x32/apps/kjumpingcube.png
usr/share/icons/hicolor/48x48/apps/kjumpingcube.png
usr/share/icons/hicolor/64x64/apps/kjumpingcube.png
usr/share/kde4/apps/kjumpingcube/kjumpingcubeui.rc
usr/share/kde4/apps/kjumpingcube/pics/default.desktop
usr/share/kde4/apps/kjumpingcube/pics/default.svg
usr/share/kde4/config.kcfg/kjumpingcube.kcfg
