/usr/share/apps/klines/*
/usr/share/applications/kde4/klines.desktop
/usr/games/klines
/usr/share/config.kcfg/klines.kcfg
/usr/share/doc/HTML/en/klines/*
/usr/share/icons/hicolor/128x128/apps/klines.png
/usr/share/icons/hicolor/64x64/apps/klines.png
/usr/share/icons/hicolor/48x48/apps/klines.png
/usr/share/icons/hicolor/32x32/apps/klines.png
/usr/share/icons/hicolor/22x22/apps/klines.png
/usr/share/icons/hicolor/16x16/apps/klines.png
../icons/klines.xpm /usr/share/pixmaps
../icons/klines-16.xpm /usr/share/pixmaps
