../icons/kmahjongg-16.xpm /usr/share/pixmaps
../icons/kmahjongg.xpm /usr/share/pixmaps
/usr/games/kmahjongg
/usr/share/applications/kde4/kmahjongg.desktop
/usr/share/doc/kde4/HTML/en/kmahjongg/*
usr/share/icons/hicolor/scalable/apps/kmahjongg.svgz
/usr/share/icons/hicolor/128x128/apps/kmahjongg.png
/usr/share/icons/hicolor/16x16/apps/kmahjongg.png
/usr/share/icons/hicolor/22x22/apps/kmahjongg.png
/usr/share/icons/hicolor/32x32/apps/kmahjongg.png
/usr/share/icons/hicolor/48x48/apps/kmahjongg.png
/usr/share/icons/hicolor/64x64/apps/kmahjongg.png
/usr/share/kde4/apps/kmahjongg/*
/usr/share/kde4/config.kcfg/kmahjongg.kcfg
