/usr/share/apps/kmahjongg/*
/usr/share/icons/hicolor/128x128/apps/kmahjongg.png
/usr/share/icons/hicolor/64x64/apps/kmahjongg.png
/usr/share/icons/hicolor/48x48/apps/kmahjongg.png
/usr/share/icons/hicolor/32x32/apps/kmahjongg.png
/usr/share/icons/hicolor/22x22/apps/kmahjongg.png
/usr/share/icons/hicolor/16x16/apps/kmahjongg.png
/usr/share/applications/kde4/kmahjongg.desktop
/usr/games/kmahjongg
/usr/share/config.kcfg/kmahjongg.kcfg
/usr/share/doc/HTML/en/kmahjongg/*
../icons/kmahjongg.xpm /usr/share/pixmaps
../icons/kmahjongg-16.xpm /usr/share/pixmaps
