../icons/kmines-16.xpm /usr/share/pixmaps
../icons/kmines.xpm /usr/share/pixmaps
usr/games/kmines
usr/share/applications/kde4/kmines.desktop
usr/share/doc/kde/HTML/en/kmines/*
usr/share/icons/hicolor/128x128/apps/kmines.png
usr/share/icons/hicolor/16x16/apps/kmines.png
usr/share/icons/hicolor/22x22/apps/kmines.png
usr/share/icons/hicolor/32x32/apps/kmines.png
usr/share/icons/hicolor/48x48/apps/kmines.png
usr/share/icons/hicolor/64x64/apps/kmines.png
usr/share/kde4/apps/kmines/*
usr/share/kde4/config/kmines.knsrc
