../icons/kreversi-16.xpm /usr/share/pixmaps
../icons/kreversi.xpm /usr/share/pixmaps
usr/games/kreversi
usr/share/applications/kde4/kreversi.desktop
usr/share/doc/kde/HTML/en/kreversi/*
usr/share/icons/hicolor/128x128/apps/kreversi.png
usr/share/icons/hicolor/16x16/apps/kreversi.png
usr/share/icons/hicolor/22x22/apps/kreversi.png
usr/share/icons/hicolor/32x32/apps/kreversi.png
usr/share/icons/hicolor/48x48/apps/kreversi.png
usr/share/icons/hicolor/64x64/apps/kreversi.png
usr/share/icons/oxygen/16x16/actions/lastmoves.png
usr/share/icons/oxygen/16x16/actions/legalmoves.png
usr/share/icons/oxygen/22x22/actions/lastmoves.png
usr/share/icons/oxygen/22x22/actions/legalmoves.png
usr/share/icons/oxygen/32x32/actions/lastmoves.png
usr/share/icons/oxygen/32x32/actions/legalmoves.png
usr/share/icons/oxygen/48x48/actions/lastmoves.png
usr/share/icons/oxygen/48x48/actions/legalmoves.png
usr/share/icons/oxygen/scalable/actions/lastmoves.svgz
usr/share/icons/oxygen/scalable/actions/legalmoves.svgz
usr/share/kde4/apps/kreversi/*
