../icons/ksame-16.xpm /usr/share/pixmaps
../icons/ksame.xpm /usr/share/pixmaps
usr/games/ksame
usr/share/applications/kde4/ksame.desktop
usr/share/doc/kde4/HTML/en/ksame/*
usr/share/icons/hicolor/128x128/apps/ksame.png
usr/share/icons/hicolor/16x16/apps/ksame.png
usr/share/icons/hicolor/22x22/apps/ksame.png
usr/share/icons/hicolor/32x32/apps/ksame.png
usr/share/icons/hicolor/48x48/apps/ksame.png
usr/share/icons/hicolor/64x64/apps/ksame.png
usr/share/kde4/apps/ksame/*
