../icons/kshisen-16.xpm /usr/share/pixmaps
../icons/kshisen.xpm /usr/share/pixmaps
usr/games/kshisen
usr/share/applications/kde4/kshisen.desktop
usr/share/doc/kde/HTML/en/kshisen/*
usr/share/icons/hicolor/128x128/apps/kshisen.png
usr/share/icons/hicolor/16x16/apps/kshisen.png
usr/share/icons/hicolor/22x22/apps/kshisen.png
usr/share/icons/hicolor/32x32/apps/kshisen.png
usr/share/icons/hicolor/48x48/apps/kshisen.png
usr/share/icons/hicolor/64x64/apps/kshisen.png
usr/share/kde4/apps/kshisen/*
usr/share/kde4/config.kcfg/kshisen.kcfg
usr/share/sounds/kshisen/tile-fall-tile.ogg
usr/share/sounds/kshisen/tile-touch.ogg
