/usr/share/applications/kde4/ksirtet.desktop
/usr/share/icons/hicolor/128x128/apps/ksirtet.png
/usr/share/icons/hicolor/64x64/apps/ksirtet.png
/usr/share/icons/hicolor/48x48/apps/ksirtet.png
/usr/share/icons/hicolor/32x32/apps/ksirtet.png
/usr/share/icons/hicolor/22x22/apps/ksirtet.png
/usr/share/icons/hicolor/16x16/apps/ksirtet.png
/usr/share/apps/ksirtet/*
/usr/games/ksirtet
/usr/share/config.kcfg/ksirtet.kcfg
/usr/share/doc/HTML/en/ksirtet/*
../icons/ksirtet.xpm /usr/share/pixmaps
../icons/ksirtet-16.xpm /usr/share/pixmaps
