../icons/kspaceduel-16.xpm /usr/share/pixmaps
../icons/kspaceduel.xpm /usr/share/pixmaps
usr/games/kspaceduel
usr/share/applications/kde4/kspaceduel.desktop
usr/share/doc/kde/HTML/en/kspaceduel/*
usr/share/icons/hicolor/128x128/apps/kspaceduel.png
usr/share/icons/hicolor/16x16/apps/kspaceduel.png
usr/share/icons/hicolor/22x22/apps/kspaceduel.png
usr/share/icons/hicolor/32x32/apps/kspaceduel.png
usr/share/icons/hicolor/48x48/apps/kspaceduel.png
usr/share/icons/hicolor/64x64/apps/kspaceduel.png
usr/share/kde4/apps/kspaceduel/*
usr/share/kde4/config.kcfg/kspaceduel.kcfg
