../icons/ksquares-16.xpm /usr/share/pixmaps
../icons/ksquares.xpm /usr/share/pixmaps
usr/games/ksquares
usr/share/applications/kde4/ksquares.desktop
usr/share/doc/kde4/HTML/en/ksquares/
usr/share/icons/hicolor/128x128/apps/ksquares.png
usr/share/icons/hicolor/16x16/apps/ksquares.png
usr/share/icons/hicolor/22x22/apps/ksquares.png
usr/share/icons/hicolor/32x32/apps/ksquares.png
usr/share/icons/hicolor/48x48/apps/ksquares.png
usr/share/icons/hicolor/64x64/apps/ksquares.png
usr/share/kde4/apps/ksquares/
usr/share/kde4/config.kcfg/ksquares.kcfg
