../icons/ksudoku-16.xpm /usr/share/pixmaps
../icons/ksudoku.xpm /usr/share/pixmaps
usr/games/ksudoku
usr/share/applications/kde4/ksudoku.desktop
usr/share/doc/kde/HTML/en/ksudoku/common
usr/share/doc/kde/HTML/en/ksudoku/index.cache.bz2
usr/share/doc/kde/HTML/en/ksudoku/index.docbook
usr/share/icons/hicolor/128x128/apps/ksudoku.png
usr/share/icons/hicolor/16x16/apps/ksudoku.png
usr/share/icons/hicolor/32x32/apps/ksudoku.png
usr/share/kde4/apps/ksudoku/
usr/share/kde4/config/ksudokurc
