/usr/games/kwin4
/usr/games/kwin4proc
/usr/share/apps/kwin4/*
/usr/share/config.kcfg/kwin4.kcfg
/usr/share/icons/hicolor/128x128/apps/kwin4.png
/usr/share/icons/hicolor/64x64/apps/kwin4.png
/usr/share/icons/hicolor/48x48/apps/kwin4.png
/usr/share/icons/hicolor/32x32/apps/kwin4.png
/usr/share/icons/hicolor/22x22/apps/kwin4.png
/usr/share/icons/hicolor/16x16/apps/kwin4.png
/usr/share/applications/kde4/kwin4.desktop
/usr/share/doc/HTML/en/kwin4/*
../icons/kwin4.xpm /usr/share/pixmaps
../icons/kwin4-16.xpm /usr/share/pixmaps
